# REST

## login
POST http://localhost:9092/admin/auth/login
Content-Type: application/json

{
    "email": "fonn8770@gmail.com",
    "password": "Kanteera/04",
    "rememberMe": false
}

## Register
## Forget Password
## Profile